package net.minecraft.init;

import java.util.Set;

import javax.annotation.Nullable;

import com.google.common.collect.Sets;

import net.minecraft.block.Block;
import net.minecraft.util.ResourceLocation;

public class Blocks
{
	public static final String AIR;
	public static final String STONE;
	public static final String GRASS;
	public static final String DIRT;
	public static final String COBBLESTONE;
	public static final String PLANKS;
	public static final String SAPLING;
	public static final String BEDROCK;
	public static final String FLOWING_WATER;
	public static final String WATER;
	public static final String FLOWING_LAVA;
	public static final String LAVA;
	public static final String SAND;
	public static final String GRAVEL;
	public static final String GOLD_ORE;
	public static final String IRON_ORE;
	public static final String COAL_ORE;
	public static final String LOG;
	public static final String LOG2;
	public static final String LEAVES;
	public static final String LEAVES2;
	public static final String SPONGE;
	public static final String GLASS;
	public static final String LAPIS_ORE;
	public static final String LAPIS_BLOCK;
	public static final String DISPENSER;
	public static final String SANDSTONE;
	public static final String NOTEBLOCK;
	public static final String BED;
	public static final String GOLDEN_RAIL;
	public static final String DETECTOR_RAIL;
	public static final String STICKY_PISTON;
	public static final String WEB;
	public static final String TALLGRASS;
	public static final String DEADBUSH;
	public static final String PISTON;
	public static final String PISTON_HEAD;
	public static final String WOOL;
	public static final String PISTON_EXTENSION;
	public static final String YELLOW_FLOWER;
	public static final String RED_FLOWER;
	public static final String BROWN_MUSHROOM;
	public static final String RED_MUSHROOM;
	public static final String GOLD_BLOCK;
	public static final String IRON_BLOCK;
	public static final String DOUBLE_STONE_SLAB;
	public static final String STONE_SLAB;
	public static final String BRICK_BLOCK;
	public static final String TNT;
	public static final String BOOKSHELF;
	public static final String MOSSY_COBBLESTONE;
	public static final String OBSIDIAN;
	public static final String TORCH;
	public static final String FIRE;
	public static final String MOB_SPAWNER;
	public static final String OAK_STAIRS;
	public static final String CHEST;
	public static final String REDSTONE_WIRE;
	public static final String DIAMOND_ORE;
	public static final String DIAMOND_BLOCK;
	public static final String CRAFTING_TABLE;
	public static final String WHEAT;
	public static final String FARMLAND;
	public static final String FURNACE;
	public static final String LIT_FURNACE;
	public static final String STANDING_SIGN;
	public static final String OAK_DOOR;
	public static final String SPRUCE_DOOR;
	public static final String BIRCH_DOOR;
	public static final String JUNGLE_DOOR;
	public static final String ACACIA_DOOR;
	public static final String DARK_OAK_DOOR;
	public static final String LADDER;
	public static final String RAIL;
	public static final String STONE_STAIRS;
	public static final String WALL_SIGN;
	public static final String LEVER;
	public static final String STONE_PRESSURE_PLATE;
	public static final String IRON_DOOR;
	public static final String WOODEN_PRESSURE_PLATE;
	public static final String REDSTONE_ORE;
	public static final String LIT_REDSTONE_ORE;
	public static final String UNLIT_REDSTONE_TORCH;
	public static final String REDSTONE_TORCH;
	public static final String STONE_BUTTON;
	public static final String SNOW_LAYER;
	public static final String ICE;
	public static final String SNOW;
	public static final String CACTUS;
	public static final String CLAY;
	public static final String REEDS;
	public static final String JUKEBOX;
	public static final String OAK_FENCE;
	public static final String SPRUCE_FENCE;
	public static final String BIRCH_FENCE;
	public static final String JUNGLE_FENCE;
	public static final String DARK_OAK_FENCE;
	public static final String ACACIA_FENCE;
	public static final String PUMPKIN;
	public static final String NETHERRACK;
	public static final String SOUL_SAND;
	public static final String GLOWSTONE;
	public static final String PORTAL;
	public static final String LIT_PUMPKIN;
	public static final String CAKE;
	public static final String UNPOWERED_REPEATER;
	public static final String POWERED_REPEATER;
	public static final String TRAPDOOR;
	public static final String MONSTER_EGG;
	public static final String STONEBRICK;
	public static final String BROWN_MUSHROOM_BLOCK;
	public static final String RED_MUSHROOM_BLOCK;
	public static final String IRON_BARS;
	public static final String GLASS_PANE;
	public static final String MELON_BLOCK;
	public static final String PUMPKIN_STEM;
	public static final String MELON_STEM;
	public static final String VINE;
	public static final String OAK_FENCE_GATE;
	public static final String SPRUCE_FENCE_GATE;
	public static final String BIRCH_FENCE_GATE;
	public static final String JUNGLE_FENCE_GATE;
	public static final String DARK_OAK_FENCE_GATE;
	public static final String ACACIA_FENCE_GATE;
	public static final String BRICK_STAIRS;
	public static final String STONE_BRICK_STAIRS;
	public static final String MYCELIUM;
	public static final String WATERLILY;
	public static final String NETHER_BRICK;
	public static final String NETHER_BRICK_FENCE;
	public static final String NETHER_BRICK_STAIRS;
	public static final String NETHER_WART;
	public static final String ENCHANTING_TABLE;
	public static final String BREWING_STAND;
	public static final String CAULDRON;
	public static final String END_PORTAL;
	public static final String END_PORTAL_FRAME;
	public static final String END_STONE;
	public static final String DRAGON_EGG;
	public static final String REDSTONE_LAMP;
	public static final String LIT_REDSTONE_LAMP;
	public static final String DOUBLE_WOODEN_SLAB;
	public static final String WOODEN_SLAB;
	public static final String COCOA;
	public static final String SANDSTONE_STAIRS;
	public static final String EMERALD_ORE;
	public static final String ENDER_CHEST;
	public static final String TRIPWIRE_HOOK;
	public static final String TRIPWIRE;
	public static final String EMERALD_BLOCK;
	public static final String SPRUCE_STAIRS;
	public static final String BIRCH_STAIRS;
	public static final String JUNGLE_STAIRS;
	public static final String COMMAND_BLOCK;
	public static final String BEACON;
	public static final String COBBLESTONE_WALL;
	public static final String FLOWER_POT;
	public static final String CARROTS;
	public static final String POTATOES;
	public static final String WOODEN_BUTTON;
	public static final String SKULL;
	public static final String ANVIL;
	public static final String TRAPPED_CHEST;
	public static final String LIGHT_WEIGHTED_PRESSURE_PLATE;
	public static final String HEAVY_WEIGHTED_PRESSURE_PLATE;
	public static final String UNPOWERED_COMPARATOR;
	public static final String POWERED_COMPARATOR;
	public static final String DAYLIGHT_DETECTOR;
	public static final String DAYLIGHT_DETECTOR_INVERTED;
	public static final String REDSTONE_BLOCK;
	public static final String QUARTZ_ORE;
	public static final String HOPPER;
	public static final String QUARTZ_BLOCK;
	public static final String QUARTZ_STAIRS;
	public static final String ACTIVATOR_RAIL;
	public static final String DROPPER;
	public static final String STAINED_HARDENED_CLAY;
	public static final String BARRIER;
	public static final String IRON_TRAPDOOR;
	public static final String HAY_BLOCK;
	public static final String CARPET;
	public static final String HARDENED_CLAY;
	public static final String COAL_BLOCK;
	public static final String PACKED_ICE;
	public static final String ACACIA_STAIRS;
	public static final String DARK_OAK_STAIRS;
	public static final String SLIME_BLOCK;
	public static final String DOUBLE_PLANT;
	public static final String STAINED_GLASS;
	public static final String STAINED_GLASS_PANE;
	public static final String PRISMARINE;
	public static final String SEA_LANTERN;
	public static final String STANDING_BANNER;
	public static final String WALL_BANNER;
	public static final String RED_SANDSTONE;
	public static final String RED_SANDSTONE_STAIRS;
	public static final String DOUBLE_STONE_SLAB2;
	public static final String STONE_SLAB2;
	public static final String END_ROD;
	public static final String CHORUS_PLANT;
	public static final String CHORUS_FLOWER;
	public static final String PURPUR_BLOCK;
	public static final String PURPUR_PILLAR;
	public static final String PURPUR_STAIRS;
	public static final String PURPUR_DOUBLE_SLAB;
	public static final String PURPUR_SLAB;
	public static final String END_BRICKS;
	public static final String BEETROOTS;
	public static final String GRASS_PATH;
	public static final String END_GATEWAY;
	public static final String REPEATING_COMMAND_BLOCK;
	public static final String CHAIN_COMMAND_BLOCK;
	public static final String FROSTED_ICE;
	public static final String MAGMA;
	public static final String NETHER_WART_BLOCK;
	public static final String RED_NETHER_BRICK;
	public static final String BONE_BLOCK;
	public static final String STRUCTURE_VOID;
	public static final String field_190976_dk;
	public static final String SHULKER_BOX_WHITE;
	public static final String SHULKER_BOX_ORANGE;
	public static final String SHULKER_BOX_MAGENTA;
	public static final String SHULKER_BOX_LIGHT_BLUE;
	public static final String SHULKER_BOX_YELLOW;
	public static final String SHULKER_BOX_LIME;
	public static final String SHULKER_BOX_PINK;
	public static final String SHULKER_BOX_GRAY;
	public static final String SHULKER_BOX_SILVER;
	public static final String SHULKER_BOX_CYAN;
	public static final String SHULKER_BOX;
	public static final String SHULKER_BOX_BLUE;
	public static final String SHULKER_BOX_BROWN;
	public static final String SHULKER_BOX_GREEN;
	public static final String SHULKER_BOX_RED;
	public static final String SHULKER_BOX_BLACK;
	public static final String field_192427_dB;
	public static final String field_192428_dC;
	public static final String field_192429_dD;
	public static final String field_192430_dE;
	public static final String field_192431_dF;
	public static final String field_192432_dG;
	public static final String field_192433_dH;
	public static final String field_192434_dI;
	public static final String field_192435_dJ;
	public static final String field_192436_dK;
	public static final String field_192437_dL;
	public static final String field_192438_dM;
	public static final String field_192439_dN;
	public static final String field_192440_dO;
	public static final String field_192441_dP;
	public static final String field_192442_dQ;
	public static final String CONCRETE;
	public static final String CONCRETE_POWDER;
	public static final String STRUCTURE_BLOCK;

	@Nullable

	/**
	 * Returns the String in the blockRegistry with the specified name.
	 */
	public static Block getBlock(String blockName)
	{
		return Block.REGISTRY.getObject(new ResourceLocation(blockName));
	}

	static
	{
		AIR = "air";
		STONE = "stone";
		GRASS = "grass";
		DIRT = "dirt";
		COBBLESTONE = "cobblestone";
		PLANKS = "planks";
		SAPLING = "sapling";
		BEDROCK = "bedrock";
		FLOWING_WATER = "flowing_water";
		WATER = "water";
		FLOWING_LAVA = "flowing_lava";
		LAVA = "lava";
		SAND = "sand";
		GRAVEL = "gravel";
		GOLD_ORE = "gold_ore";
		IRON_ORE = "iron_ore";
		COAL_ORE = "coal_ore";
		LOG = "log";
		LOG2 = "log2";
		LEAVES = "leaves";
		LEAVES2 = "leaves2";
		SPONGE = "sponge";
		GLASS = "glass";
		LAPIS_ORE = "lapis_ore";
		LAPIS_BLOCK = "lapis_block";
		DISPENSER = "dispenser";
		SANDSTONE = "sandstone";
		NOTEBLOCK = "noteblock";
		BED = "bed";
		GOLDEN_RAIL = "golden_rail";
		DETECTOR_RAIL = "detector_rail";
		STICKY_PISTON = "sticky_piston";
		WEB = "web";
		TALLGRASS = "tallgrass";
		DEADBUSH = "deadbush";
		PISTON = "piston";
		PISTON_HEAD = "piston_head";
		WOOL = "wool";
		PISTON_EXTENSION = "piston_extension";
		YELLOW_FLOWER = "yellow_flower";
		RED_FLOWER = "red_flower";
		BROWN_MUSHROOM = "brown_mushroom";
		RED_MUSHROOM = "red_mushroom";
		GOLD_BLOCK = "gold_block";
		IRON_BLOCK = "iron_block";
		DOUBLE_STONE_SLAB = "double_stone_slab";
		STONE_SLAB = "stone_slab";
		BRICK_BLOCK = "brick_block";
		TNT = "tnt";
		BOOKSHELF = "bookshelf";
		MOSSY_COBBLESTONE = "mossy_cobblestone";
		OBSIDIAN = "obsidian";
		TORCH = "torch";
		FIRE = "fire";
		MOB_SPAWNER = "mob_spawner";
		OAK_STAIRS = "oak_stairs";
		CHEST = "chest";
		REDSTONE_WIRE = "redstone_wire";
		DIAMOND_ORE = "diamond_ore";
		DIAMOND_BLOCK = "diamond_block";
		CRAFTING_TABLE = "crafting_table";
		WHEAT = "wheat";
		FARMLAND = "farmland";
		FURNACE = "furnace";
		LIT_FURNACE = "lit_furnace";
		STANDING_SIGN = "standing_sign";
		OAK_DOOR = "wooden_door";
		SPRUCE_DOOR = "spruce_door";
		BIRCH_DOOR = "birch_door";
		JUNGLE_DOOR = "jungle_door";
		ACACIA_DOOR = "acacia_door";
		DARK_OAK_DOOR = "dark_oak_door";
		LADDER = "ladder";
		RAIL = "rail";
		STONE_STAIRS = "stone_stairs";
		WALL_SIGN = "wall_sign";
		LEVER = "lever";
		STONE_PRESSURE_PLATE = "stone_pressure_plate";
		IRON_DOOR = "iron_door";
		WOODEN_PRESSURE_PLATE = "wooden_pressure_plate";
		REDSTONE_ORE = "redstone_ore";
		LIT_REDSTONE_ORE = "lit_redstone_ore";
		UNLIT_REDSTONE_TORCH = "unlit_redstone_torch";
		REDSTONE_TORCH = "redstone_torch";
		STONE_BUTTON = "stone_button";
		SNOW_LAYER = "snow_layer";
		ICE = "ice";
		SNOW = "snow";
		CACTUS = "cactus";
		CLAY = "clay";
		REEDS = "reeds";
		JUKEBOX = "jukebox";
		OAK_FENCE = "fence";
		SPRUCE_FENCE = "spruce_fence";
		BIRCH_FENCE = "birch_fence";
		JUNGLE_FENCE = "jungle_fence";
		DARK_OAK_FENCE = "dark_oak_fence";
		ACACIA_FENCE = "acacia_fence";
		PUMPKIN = "pumpkin";
		NETHERRACK = "netherrack";
		SOUL_SAND = "soul_sand";
		GLOWSTONE = "glowstone";
		PORTAL = "portal";
		LIT_PUMPKIN = "lit_pumpkin";
		CAKE = "cake";
		UNPOWERED_REPEATER = "unpowered_repeater";
		POWERED_REPEATER = "powered_repeater";
		TRAPDOOR = "trapdoor";
		MONSTER_EGG = "monster_egg";
		STONEBRICK = "stonebrick";
		BROWN_MUSHROOM_BLOCK = "brown_mushroom_block";
		RED_MUSHROOM_BLOCK = "red_mushroom_block";
		IRON_BARS = "iron_bars";
		GLASS_PANE = "glass_pane";
		MELON_BLOCK = "melon_block";
		PUMPKIN_STEM = "pumpkin_stem";
		MELON_STEM = "melon_stem";
		VINE = "vine";
		OAK_FENCE_GATE = "fence_gate";
		SPRUCE_FENCE_GATE = "spruce_fence_gate";
		BIRCH_FENCE_GATE = "birch_fence_gate";
		JUNGLE_FENCE_GATE = "jungle_fence_gate";
		DARK_OAK_FENCE_GATE = "dark_oak_fence_gate";
		ACACIA_FENCE_GATE = "acacia_fence_gate";
		BRICK_STAIRS = "brick_stairs";
		STONE_BRICK_STAIRS = "stone_brick_stairs";
		MYCELIUM = "mycelium";
		WATERLILY = "waterlily";
		NETHER_BRICK = "nether_brick";
		NETHER_BRICK_FENCE = "nether_brick_fence";
		NETHER_BRICK_STAIRS = "nether_brick_stairs";
		NETHER_WART = "nether_wart";
		ENCHANTING_TABLE = "enchanting_table";
		BREWING_STAND = "brewing_stand";
		CAULDRON = "cauldron";
		END_PORTAL = "end_portal";
		END_PORTAL_FRAME = "end_portal_frame";
		END_STONE = "end_stone";
		DRAGON_EGG = "dragon_egg";
		REDSTONE_LAMP = "redstone_lamp";
		LIT_REDSTONE_LAMP = "lit_redstone_lamp";
		DOUBLE_WOODEN_SLAB = "double_wooden_slab";
		WOODEN_SLAB = "wooden_slab";
		COCOA = "cocoa";
		SANDSTONE_STAIRS = "sandstone_stairs";
		EMERALD_ORE = "emerald_ore";
		ENDER_CHEST = "ender_chest";
		TRIPWIRE_HOOK = "tripwire_hook";
		TRIPWIRE = "tripwire";
		EMERALD_BLOCK = "emerald_block";
		SPRUCE_STAIRS = "spruce_stairs";
		BIRCH_STAIRS = "birch_stairs";
		JUNGLE_STAIRS = "jungle_stairs";
		COMMAND_BLOCK = "command_block";
		BEACON = "beacon";
		COBBLESTONE_WALL = "cobblestone_wall";
		FLOWER_POT = "flower_pot";
		CARROTS = "carrots";
		POTATOES = "potatoes";
		WOODEN_BUTTON = "wooden_button";
		SKULL = "skull";
		ANVIL = "anvil";
		TRAPPED_CHEST = "trapped_chest";
		LIGHT_WEIGHTED_PRESSURE_PLATE = "light_weighted_pressure_plate";
		HEAVY_WEIGHTED_PRESSURE_PLATE = "heavy_weighted_pressure_plate";
		UNPOWERED_COMPARATOR = "unpowered_comparator";
		POWERED_COMPARATOR = "powered_comparator";
		DAYLIGHT_DETECTOR = "daylight_detector";
		DAYLIGHT_DETECTOR_INVERTED = "daylight_detector_inverted";
		REDSTONE_BLOCK = "redstone_block";
		QUARTZ_ORE = "quartz_ore";
		HOPPER = "hopper";
		QUARTZ_BLOCK = "quartz_block";
		QUARTZ_STAIRS = "quartz_stairs";
		ACTIVATOR_RAIL = "activator_rail";
		DROPPER = "dropper";
		STAINED_HARDENED_CLAY = "stained_hardened_clay";
		BARRIER = "barrier";
		IRON_TRAPDOOR = "iron_trapdoor";
		HAY_BLOCK = "hay_block";
		CARPET = "carpet";
		HARDENED_CLAY = "hardened_clay";
		COAL_BLOCK = "coal_block";
		PACKED_ICE = "packed_ice";
		ACACIA_STAIRS = "acacia_stairs";
		DARK_OAK_STAIRS = "dark_oak_stairs";
		SLIME_BLOCK = "slime";
		DOUBLE_PLANT = "double_plant";
		STAINED_GLASS = "stained_glass";
		STAINED_GLASS_PANE = "stained_glass_pane";
		PRISMARINE = "prismarine";
		SEA_LANTERN = "sea_lantern";
		STANDING_BANNER = "standing_banner";
		WALL_BANNER = "wall_banner";
		RED_SANDSTONE = "red_sandstone";
		RED_SANDSTONE_STAIRS = "red_sandstone_stairs";
		DOUBLE_STONE_SLAB2 = "double_stone_slab2";
		STONE_SLAB2 = "stone_slab2";
		END_ROD = "end_rod";
		CHORUS_PLANT = "chorus_plant";
		CHORUS_FLOWER = "chorus_flower";
		PURPUR_BLOCK = "purpur_block";
		PURPUR_PILLAR = "purpur_pillar";
		PURPUR_STAIRS = "purpur_stairs";
		PURPUR_DOUBLE_SLAB = "purpur_double_slab";
		PURPUR_SLAB = "purpur_slab";
		END_BRICKS = "end_bricks";
		BEETROOTS = "beetroots";
		GRASS_PATH = "grass_path";
		END_GATEWAY = "end_gateway";
		REPEATING_COMMAND_BLOCK = "repeating_command_block";
		CHAIN_COMMAND_BLOCK = "chain_command_block";
		FROSTED_ICE = "frosted_ice";
		MAGMA = "magma";
		NETHER_WART_BLOCK = "nether_wart_block";
		RED_NETHER_BRICK = "red_nether_brick";
		BONE_BLOCK = "bone_block";
		STRUCTURE_VOID = "structure_void";
		field_190976_dk = "observer";
		SHULKER_BOX_WHITE = "white_shulker_box";
		SHULKER_BOX_ORANGE = "orange_shulker_box";
		SHULKER_BOX_MAGENTA = "magenta_shulker_box";
		SHULKER_BOX_LIGHT_BLUE = "light_blue_shulker_box";
		SHULKER_BOX_YELLOW = "yellow_shulker_box";
		SHULKER_BOX_LIME = "lime_shulker_box";
		SHULKER_BOX_PINK = "pink_shulker_box";
		SHULKER_BOX_GRAY = "gray_shulker_box";
		SHULKER_BOX_SILVER = "silver_shulker_box";
		SHULKER_BOX_CYAN = "cyan_shulker_box";
		SHULKER_BOX = "purple_shulker_box";
		SHULKER_BOX_BLUE = "blue_shulker_box";
		SHULKER_BOX_BROWN = "brown_shulker_box";
		SHULKER_BOX_GREEN = "green_shulker_box";
		SHULKER_BOX_RED = "red_shulker_box";
		SHULKER_BOX_BLACK = "black_shulker_box";
		field_192427_dB = "white_glazed_terracotta";
		field_192428_dC = "orange_glazed_terracotta";
		field_192429_dD = "magenta_glazed_terracotta";
		field_192430_dE = "light_blue_glazed_terracotta";
		field_192431_dF = "yellow_glazed_terracotta";
		field_192432_dG = "lime_glazed_terracotta";
		field_192433_dH = "pink_glazed_terracotta";
		field_192434_dI = "gray_glazed_terracotta";
		field_192435_dJ = "silver_glazed_terracotta";
		field_192436_dK = "cyan_glazed_terracotta";
		field_192437_dL = "purple_glazed_terracotta";
		field_192438_dM = "blue_glazed_terracotta";
		field_192439_dN = "brown_glazed_terracotta";
		field_192440_dO = "green_glazed_terracotta";
		field_192441_dP = "red_glazed_terracotta";
		field_192442_dQ = "black_glazed_terracotta";
		CONCRETE = "concrete";
		CONCRETE_POWDER = "concrete_powder";
		STRUCTURE_BLOCK = "structure_block";
	}
}
