package net.minecraft.init;

import net.minecraft.item.Item;
import net.minecraft.item.ItemBow;
import net.minecraft.util.ResourceLocation;

public class Items
{
	public static final String AIR;
	public static final String IRON_SHOVEL;
	public static final String IRON_PICKAXE;
	public static final String IRON_AXE;
	public static final String FLINT_AND_STEEL;
	public static final String APPLE;
	public static final String BOW;
	public static final String ARROW;
	public static final String SPECTRAL_ARROW;
	public static final String TIPPED_ARROW;
	public static final String OLD_COAL;
	public static final String OLD_DIAMOND;
	public static final String OLD_IRON_INGOT;
	public static final String OLD_GOLD_INGOT;
	public static final String IRON_SWORD;
	public static final String WOODEN_SWORD;
	public static final String WOODEN_SHOVEL;
	public static final String WOODEN_PICKAXE;
	public static final String WOODEN_AXE;
	public static final String STONE_SWORD;
	public static final String STONE_SHOVEL;
	public static final String STONE_PICKAXE;
	public static final String STONE_AXE;
	public static final String DIAMOND_SWORD;
	public static final String DIAMOND_SHOVEL;
	public static final String DIAMOND_PICKAXE;
	public static final String DIAMOND_AXE;
	public static final String STICK;
	public static final String BOWL;
	public static final String MUSHROOM_STEW;
	public static final String GOLDEN_SWORD;
	public static final String GOLDEN_SHOVEL;
	public static final String GOLDEN_PICKAXE;
	public static final String GOLDEN_AXE;
	public static final String STRING;
	public static final String FEATHER;
	public static final String GUNPOWDER;
	public static final String WOODEN_HOE;
	public static final String STONE_HOE;
	public static final String IRON_HOE;
	public static final String DIAMOND_HOE;
	public static final String GOLDEN_HOE;
	public static final String WHEAT_SEEDS;
	public static final String WHEAT;
	public static final String BREAD;
	public static final String LEATHER_HELMET;
	public static final String LEATHER_CHESTPLATE;
	public static final String LEATHER_LEGGINGS;
	public static final String LEATHER_BOOTS;
	public static final String CHAINMAIL_HELMET;
	public static final String CHAINMAIL_CHESTPLATE;
	public static final String CHAINMAIL_LEGGINGS;
	public static final String CHAINMAIL_BOOTS;
	public static final String IRON_HELMET;
	public static final String IRON_CHESTPLATE;
	public static final String IRON_LEGGINGS;
	public static final String IRON_BOOTS;
	public static final String DIAMOND_HELMET;
	public static final String DIAMOND_CHESTPLATE;
	public static final String DIAMOND_LEGGINGS;
	public static final String DIAMOND_BOOTS;
	public static final String GOLDEN_HELMET;
	public static final String GOLDEN_CHESTPLATE;
	public static final String GOLDEN_LEGGINGS;
	public static final String GOLDEN_BOOTS;
	public static final String FLINT;
	public static final String PORKCHOP;
	public static final String COOKED_PORKCHOP;
	public static final String PAINTING;
	public static final String GOLDEN_APPLE;
	public static final String SIGN;
	public static final String OAK_DOOR;
	public static final String SPRUCE_DOOR;
	public static final String BIRCH_DOOR;
	public static final String JUNGLE_DOOR;
	public static final String ACACIA_DOOR;
	public static final String DARK_OAK_DOOR;
	public static final String BUCKET;
	public static final String WATER_BUCKET;
	public static final String LAVA_BUCKET;
	public static final String MINECART;
	public static final String SADDLE;
	public static final String IRON_DOOR;
	public static final String REDSTONE;
	public static final String SNOWBALL;
	public static final String BOAT;
	public static final String SPRUCE_BOAT;
	public static final String BIRCH_BOAT;
	public static final String JUNGLE_BOAT;
	public static final String ACACIA_BOAT;
	public static final String DARK_OAK_BOAT;
	public static final String LEATHER;
	public static final String MILK_BUCKET;
	public static final String BRICK;
	public static final String CLAY_BALL;
	public static final String REEDS;
	public static final String PAPER;
	public static final String BOOK;
	public static final String SLIME_BALL;
	public static final String CHEST_MINECART;
	public static final String FURNACE_MINECART;
	public static final String EGG;
	public static final String COMPASS;
	public static final String FISHING_ROD;
	public static final String CLOCK;
	public static final String GLOWSTONE_DUST;
	public static final String FISH;
	public static final String COOKED_FISH;
	public static final String DYE;
	public static final String BONE;
	public static final String SUGAR;
	public static final String CAKE;
	public static final String BED;
	public static final String REPEATER;
	public static final String COOKIE;
	public static final String FILLED_MAP;
	public static final String SHEARS;
	public static final String MELON;
	public static final String PUMPKIN_SEEDS;
	public static final String MELON_SEEDS;
	public static final String BEEF;
	public static final String COOKED_BEEF;
	public static final String CHICKEN;
	public static final String COOKED_CHICKEN;
	public static final String MUTTON;
	public static final String COOKED_MUTTON;
	public static final String RABBIT;
	public static final String COOKED_RABBIT;
	public static final String RABBIT_STEW;
	public static final String RABBIT_FOOT;
	public static final String RABBIT_HIDE;
	public static final String ROTTEN_FLESH;
	public static final String ENDER_PEARL;
	public static final String BLAZE_ROD;
	public static final String GHAST_TEAR;
	public static final String GOLD_NUGGET;
	public static final String NETHER_WART;
	public static final String POTIONITEM;
	public static final String SPLASH_POTION;
	public static final String LINGERING_POTION;
	public static final String GLASS_BOTTLE;
	public static final String DRAGON_BREATH;
	public static final String SPIDER_EYE;
	public static final String FERMENTED_SPIDER_EYE;
	public static final String BLAZE_POWDER;
	public static final String MAGMA_CREAM;
	public static final String BREWING_STAND;
	public static final String CAULDRON;
	public static final String ENDER_EYE;
	public static final String SPECKLED_MELON;
	public static final String SPAWN_EGG;
	public static final String EXPERIENCE_BOTTLE;
	public static final String FIRE_CHARGE;
	public static final String WRITABLE_BOOK;
	public static final String WRITTEN_BOOK;
	public static final String EMERALD;
	public static final String ITEM_FRAME;
	public static final String FLOWER_POT;
	public static final String CARROT;
	public static final String POTATO;
	public static final String BAKED_POTATO;
	public static final String POISONOUS_POTATO;
	public static final String MAP;
	public static final String GOLDEN_CARROT;
	public static final String SKULL;
	public static final String CARROT_ON_A_STICK;
	public static final String NETHER_STAR;
	public static final String PUMPKIN_PIE;
	public static final String FIREWORKS;
	public static final String FIREWORK_CHARGE;
	public static final String ENCHANTED_BOOK;
	public static final String COMPARATOR;
	public static final String NETHERBRICK;
	public static final String QUARTZ;
	public static final String TNT_MINECART;
	public static final String HOPPER_MINECART;
	public static final String ARMOR_STAND;
	public static final String IRON_HORSE_ARMOR;
	public static final String GOLDEN_HORSE_ARMOR;
	public static final String DIAMOND_HORSE_ARMOR;
	public static final String LEAD;
	public static final String NAME_TAG;
	public static final String COMMAND_BLOCK_MINECART;
	public static final String RECORD_13;
	public static final String RECORD_CAT;
	public static final String RECORD_BLOCKS;
	public static final String RECORD_CHIRP;
	public static final String RECORD_FAR;
	public static final String RECORD_MALL;
	public static final String RECORD_MELLOHI;
	public static final String RECORD_STAL;
	public static final String RECORD_STRAD;
	public static final String RECORD_WARD;
	public static final String RECORD_11;
	public static final String RECORD_WAIT;
	public static final String PRISMARINE_SHARD;
	public static final String PRISMARINE_CRYSTALS;
	public static final String BANNER;
	public static final String END_CRYSTAL;
	public static final String SHIELD;
	public static final String ELYTRA;
	public static final String CHORUS_FRUIT;
	public static final String CHORUS_FRUIT_POPPED;
	public static final String BEETROOT_SEEDS;
	public static final String BEETROOT;
	public static final String BEETROOT_SOUP;
	public static final String TOTEM;
	public static final String SHULKER_SHELL;
	public static final String IRON_NUGGET;
	public static final String KNOWLEDGE_BOOK;

	public static Item getItem(String name)
	{
		Item item = Item.REGISTRY.getObject(new ResourceLocation(name));

		if (item == null)
		{
			return Items.getItem(Items.AIR);
		}
		else
		{
			return item;
		}
	}

	static
	{

		AIR = "air";
		IRON_SHOVEL = "iron_shovel";
		IRON_PICKAXE = "iron_pickaxe";
		IRON_AXE = "iron_axe";
		FLINT_AND_STEEL = "flint_and_steel";
		APPLE = "apple";
		BOW = "bow";
		ARROW = "arrow";
		SPECTRAL_ARROW = "spectral_arrow";
		TIPPED_ARROW = "tipped_arrow";
		OLD_COAL = "coal";
		OLD_DIAMOND = "diamond";
		OLD_IRON_INGOT = "iron_ingot";
		OLD_GOLD_INGOT = "gold_ingot";
		IRON_SWORD = "iron_sword";
		WOODEN_SWORD = "wooden_sword";
		WOODEN_SHOVEL = "wooden_shovel";
		WOODEN_PICKAXE = "wooden_pickaxe";
		WOODEN_AXE = "wooden_axe";
		STONE_SWORD = "stone_sword";
		STONE_SHOVEL = "stone_shovel";
		STONE_PICKAXE = "stone_pickaxe";
		STONE_AXE = "stone_axe";
		DIAMOND_SWORD = "diamond_sword";
		DIAMOND_SHOVEL = "diamond_shovel";
		DIAMOND_PICKAXE = "diamond_pickaxe";
		DIAMOND_AXE = "diamond_axe";
		STICK = "stick";
		BOWL = "bowl";
		MUSHROOM_STEW = "mushroom_stew";
		GOLDEN_SWORD = "golden_sword";
		GOLDEN_SHOVEL = "golden_shovel";
		GOLDEN_PICKAXE = "golden_pickaxe";
		GOLDEN_AXE = "golden_axe";
		STRING = "string";
		FEATHER = "feather";
		GUNPOWDER = "gunpowder";
		WOODEN_HOE = "wooden_hoe";
		STONE_HOE = "stone_hoe";
		IRON_HOE = "iron_hoe";
		DIAMOND_HOE = "diamond_hoe";
		GOLDEN_HOE = "golden_hoe";
		WHEAT_SEEDS = "wheat_seeds";
		WHEAT = "wheat";
		BREAD = "bread";
		LEATHER_HELMET = "leather_helmet";
		LEATHER_CHESTPLATE = "leather_chestplate";
		LEATHER_LEGGINGS = "leather_leggings";
		LEATHER_BOOTS = "leather_boots";
		CHAINMAIL_HELMET = "chainmail_helmet";
		CHAINMAIL_CHESTPLATE = "chainmail_chestplate";
		CHAINMAIL_LEGGINGS = "chainmail_leggings";
		CHAINMAIL_BOOTS = "chainmail_boots";
		IRON_HELMET = "iron_helmet";
		IRON_CHESTPLATE = "iron_chestplate";
		IRON_LEGGINGS = "iron_leggings";
		IRON_BOOTS = "iron_boots";
		DIAMOND_HELMET = "diamond_helmet";
		DIAMOND_CHESTPLATE = "diamond_chestplate";
		DIAMOND_LEGGINGS = "diamond_leggings";
		DIAMOND_BOOTS = "diamond_boots";
		GOLDEN_HELMET = "golden_helmet";
		GOLDEN_CHESTPLATE = "golden_chestplate";
		GOLDEN_LEGGINGS = "golden_leggings";
		GOLDEN_BOOTS = "golden_boots";
		FLINT = "flint";
		PORKCHOP = "porkchop";
		COOKED_PORKCHOP = "cooked_porkchop";
		PAINTING = "painting";
		GOLDEN_APPLE = "golden_apple";
		SIGN = "sign";
		OAK_DOOR = "wooden_door";
		SPRUCE_DOOR = "spruce_door";
		BIRCH_DOOR = "birch_door";
		JUNGLE_DOOR = "jungle_door";
		ACACIA_DOOR = "acacia_door";
		DARK_OAK_DOOR = "dark_oak_door";
		BUCKET = "bucket";
		WATER_BUCKET = "water_bucket";
		LAVA_BUCKET = "lava_bucket";
		MINECART = "minecart";
		SADDLE = "saddle";
		IRON_DOOR = "iron_door";
		REDSTONE = "redstone";
		SNOWBALL = "snowball";
		BOAT = "boat";
		SPRUCE_BOAT = "spruce_boat";
		BIRCH_BOAT = "birch_boat";
		JUNGLE_BOAT = "jungle_boat";
		ACACIA_BOAT = "acacia_boat";
		DARK_OAK_BOAT = "dark_oak_boat";
		LEATHER = "leather";
		MILK_BUCKET = "milk_bucket";
		BRICK = "brick";
		CLAY_BALL = "clay_ball";
		REEDS = "reeds";
		PAPER = "paper";
		BOOK = "book";
		SLIME_BALL = "slime_ball";
		CHEST_MINECART = "chest_minecart";
		FURNACE_MINECART = "furnace_minecart";
		EGG = "egg";
		COMPASS = "compass";
		FISHING_ROD = "fishing_rod";
		CLOCK = "clock";
		GLOWSTONE_DUST = "glowstone_dust";
		FISH = "fish";
		COOKED_FISH = "cooked_fish";
		DYE = "dye";
		BONE = "bone";
		SUGAR = "sugar";
		CAKE = "cake";
		BED = "bed";
		REPEATER = "repeater";
		COOKIE = "cookie";
		FILLED_MAP = "filled_map";
		SHEARS = "shears";
		MELON = "melon";
		PUMPKIN_SEEDS = "pumpkin_seeds";
		MELON_SEEDS = "melon_seeds";
		BEEF = "beef";
		COOKED_BEEF = "cooked_beef";
		CHICKEN = "chicken";
		COOKED_CHICKEN = "cooked_chicken";
		MUTTON = "mutton";
		COOKED_MUTTON = "cooked_mutton";
		RABBIT = "rabbit";
		COOKED_RABBIT = "cooked_rabbit";
		RABBIT_STEW = "rabbit_stew";
		RABBIT_FOOT = "rabbit_foot";
		RABBIT_HIDE = "rabbit_hide";
		ROTTEN_FLESH = "rotten_flesh";
		ENDER_PEARL = "ender_pearl";
		BLAZE_ROD = "blaze_rod";
		GHAST_TEAR = "ghast_tear";
		GOLD_NUGGET = "gold_nugget";
		NETHER_WART = "nether_wart";
		POTIONITEM = "potion";
		SPLASH_POTION = "splash_potion";
		LINGERING_POTION = "lingering_potion";
		GLASS_BOTTLE = "glass_bottle";
		DRAGON_BREATH = "dragon_breath";
		SPIDER_EYE = "spider_eye";
		FERMENTED_SPIDER_EYE = "fermented_spider_eye";
		BLAZE_POWDER = "blaze_powder";
		MAGMA_CREAM = "magma_cream";
		BREWING_STAND = "brewing_stand";
		CAULDRON = "cauldron";
		ENDER_EYE = "ender_eye";
		SPECKLED_MELON = "speckled_melon";
		SPAWN_EGG = "spawn_egg";
		EXPERIENCE_BOTTLE = "experience_bottle";
		FIRE_CHARGE = "fire_charge";
		WRITABLE_BOOK = "writable_book";
		WRITTEN_BOOK = "written_book";
		EMERALD = "emerald";
		ITEM_FRAME = "item_frame";
		FLOWER_POT = "flower_pot";
		CARROT = "carrot";
		POTATO = "potato";
		BAKED_POTATO = "baked_potato";
		POISONOUS_POTATO = "poisonous_potato";
		MAP = "map";
		GOLDEN_CARROT = "golden_carrot";
		SKULL = "skull";
		CARROT_ON_A_STICK = "carrot_on_a_stick";
		NETHER_STAR = "nether_star";
		PUMPKIN_PIE = "pumpkin_pie";
		FIREWORKS = "fireworks";
		FIREWORK_CHARGE = "firework_charge";
		ENCHANTED_BOOK = "enchanted_book";
		COMPARATOR = "comparator";
		NETHERBRICK = "netherbrick";
		QUARTZ = "quartz";
		TNT_MINECART = "tnt_minecart";
		HOPPER_MINECART = "hopper_minecart";
		ARMOR_STAND = "armor_stand";
		IRON_HORSE_ARMOR = "iron_horse_armor";
		GOLDEN_HORSE_ARMOR = "golden_horse_armor";
		DIAMOND_HORSE_ARMOR = "diamond_horse_armor";
		LEAD = "lead";
		NAME_TAG = "name_tag";
		COMMAND_BLOCK_MINECART = "command_block_minecart";
		RECORD_13 = "record_13";
		RECORD_CAT = "record_cat";
		RECORD_BLOCKS = "record_blocks";
		RECORD_CHIRP = "record_chirp";
		RECORD_FAR = "record_far";
		RECORD_MALL = "record_mall";
		RECORD_MELLOHI = "record_mellohi";
		RECORD_STAL = "record_stal";
		RECORD_STRAD = "record_strad";
		RECORD_WARD = "record_ward";
		RECORD_11 = "record_11";
		RECORD_WAIT = "record_wait";
		PRISMARINE_SHARD = "prismarine_shard";
		PRISMARINE_CRYSTALS = "prismarine_crystals";
		BANNER = "banner";
		END_CRYSTAL = "end_crystal";
		SHIELD = "shield";
		ELYTRA = "elytra";
		CHORUS_FRUIT = "chorus_fruit";
		CHORUS_FRUIT_POPPED = "chorus_fruit_popped";
		BEETROOT_SEEDS = "beetroot_seeds";
		BEETROOT = "beetroot";
		BEETROOT_SOUP = "beetroot_soup";
		TOTEM = "totem_of_undying";
		SHULKER_SHELL = "shulker_shell";
		IRON_NUGGET = "iron_nugget";
		KNOWLEDGE_BOOK = "knowledge_book";
	}
}
